### ISSUE TITLE
Weird formatting on vector slice with arithmetic

### ISSUE THREAD

**Issue by ynadji** [zeek/zeekscript#12]
So this guy:

```zeek
local frag_len = bytestring_to_count(data[ mres$off - 1 + 8 : mres$off - 1 + 10 ]);
```

becomes

```zeek
        local frag_len = bytestring_to_count(data[mres$off - 1
            + 8:mres$off - 1
            + 10]);
```

which, well, looks kinda ugly to me. Not sure what the Right Way to ident this is. If I add parens around the two halves of the splice, it stays on one line at least:

```zeek
local frag_len = bytestring_to_count(data[( mres$off - 1 + 8 ):( mres$off - 1 + 10 )]);
```

**Comment by ckreibich** [comment]
Thanks Yacin! Just to explain where this comes from: the idea here was that we occasionally have really long strings scripts that could instead be broken up into shorter ones, concatenated with "+", that will look nicely structured with the alignment around "+". But, this missed the fact that "+" can of course also be part of more complex arithmetic.

It should be feasible to keep the existing improvement and just focus it on "additions" of strings.

**Comment by ynadji** [comment]
Ahh that makes a lot of sense. Thanks for explaining.
