### ISSUE TITLE
Add text editor integration for sublime

### ISSUE THREAD

**Issue by ynadji** [zeek/zeekscript#15]
Integrate through 3rd party [zeek plugin](https://github.com/zeek/zeek-sublime)

**Comment by bbannier** [comment]
Closing as this is less something zeek-format should do, and more about an integration picking it up.

That being said, a language server can provide this and https://github.com/bbannier/zeek-language-server (the only Zeek language server I am aware of) already provides zeekf-format integration. Information on how to wire up a LSP server is documented in the [Sublime docs](https://lsp.readthedocs.io/en/stable/).

If you strongly feel that this should be implemented outside of a language server, please open an issue (or even better a PR) against zeek/zeek-sublime.
