### ISSUE TITLE
Recursively analyzing directories

### ISSUE THREAD

**Issue by vpax** [zeek/zeekscript#2]
It would be cool that by giving zeek-script a directory argument, it recursively formatted every `.zeek` file in it or its subdirectories.  This only makes sense for `-i`, so it should check for that, too.

OTOH, it's not hard to script this up with `find` and `xargs`, so I can see viewing it as uneccessary complexity.

**Comment by ckreibich** [comment]
It's now there Vern:

```
$ cd zeek
$ zeek-format -ir scripts
430 files processed successfully
```

**Comment by vpax** [comment]
w00t!
