### ISSUE TITLE
typo : --inline should be --inplace

### ISSUE THREAD

**Issue by benjeems** [zeek/zeekscript#22]
(nit) small typo in help text --inline

$ zeek-format -r --inline *
usage: zeek-format [-h] [--version] [--inplace] [--recursive] [FILES ...]
zeek-format: error: unrecognized arguments: --inline

**Comment by ckreibich** [comment]
Thank you Ben, this should already be fixed in `main` via 199e1d4bac4c4cfb1903b1fcf318b932545b4f7d. Let me know if I'm missing anything.
