### ISSUE TITLE
Formatting of initializer lists

### ISSUE THREAD

**Issue by vpax** [zeek/zeekscript#3]
I think we need more flexibility in how these are done.  While I get the general notion of one-initializer-per-line, and that will often be the desired way to go, this looks strange for things like large vectors of numbers that really don't need to be called out per-element.  Here's an example from code I'm working on:

> const deltas1: vector of double = {
        0.01,
        0.02,
        0.01,
        0.01,
        0.02,
        0.01,
        0.01,
        0.02,
        0.01,
        0.01,
        0.02,
        0.01,
        0.01,
        0.02,
        0.01,
        0.01,
        0.02
};

(where the numbers are indented, even though GitHub formatting doesn't show that)

**Comment by ckreibich** [comment]
Good one, yeah. The insistence on newlines stems from stuff like 

```
        const dll_characteristics: table[count] of string = {
                [0x40]   = "DYNAMIC_BASE",
                [0x80]   = "FORCE_INTEGRITY",
                [0x100]  = "NX_COMPAT",
                [0x200]  = "NO_ISOLATION",
                [0x400]  = "NO_SEH",
                ...
```

which look better that way, even for long lists. But these are tables, not vectors, and I'm thinking vectors might naturally make more sense to lay out densely.

Btw, I've generally been trying to avoid piling in all kinds of fancy heuristics. They often come to mind, but I've found they also quickly make reasoning brittle.

**Comment by ckreibich** [comment]
There's now logic that takes the existing formatting of various lists as a clue as to how to format. Specifically, presence of comments in such constructs now leads to linebreaks, while otherwise preserving single-line layout. Example:

```
const deltas1: vector of double = {
0.01,
0.02, # oh yay
0.01, 0.01, 0.02, # oh my
0.01 };

const deltas2: vector of double = { 0.01, 0.02, 0.01, 0.01, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01 };
```

becomes

```
const deltas1: vector of double = {
        0.01,
        0.02, # oh yay
        0.01,
        0.01,
        0.02, # oh my
        0.01
};

const deltas2: vector of double = { 0.01, 0.02, 0.01, 0.01, 0.02, 0.01, 0.01,
    0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01 };
```
