### ISSUE TITLE
Unnecessary initializers

### ISSUE THREAD

**Issue by vpax** [zeek/zeekscript#32]
My style guide says to avoid unnecessary initializers, such as:
> global my_vec: vector of count = vector();

I'd like this to instead be changed to:
> global my_vec: vector of count;

Is that a reasonable `zeek-format` feature?  Or should I just leave it as an element in the style guide?

**Comment by bbannier** [comment]
AFAICT the parser doesn't have enough of an understanding to decide which RHS adds something and which one doesn't.

On the clang side something like this wouldn't be handled by `clang-format` which has a similarly limited understanding of the code, but instead in a `clang-tidy` lint with an automatable fixit.

**Comment by vpax** [comment]
Ah, yeah, that makes sense.  Okay, I'll just address it in the style guide.
