### ISSUE TITLE
Consider using TOX or NOX for testing against supported versions of python

### ISSUE THREAD

**Issue by ottobackwards** [zeek/zeekscript#38]

**Comment by ckreibich** [comment]
The existing [matrix](https://github.com/zeek/zeekscript/blob/main/.github/workflows/build_wheels.yml) covers Python 3.7 - 3.11 on ubuntu-20.04, windows-2019, macos-10.15, macos-11. I think that addresses this, so I'm going to close this ticket.

**Comment by ottobackwards** [comment]
Can I run that locally?  If you use nox or tox then local dev work is covered
