### ISSUE TITLE
This package needs a release

### ISSUE THREAD

**Issue by bbannier** [zeek/zeekscript#42]
We recommend installation of the package on pypi with `pip`. The version published there is almost 9 months old and does not contain fixes for critical data loss issues fixed in the meantime. We should publish a new release as soon as possible.

**Comment by ckreibich** [comment]
I hang my head in shame. Done!

https://github.com/zeek/zeekscript/releases/tag/v1.2.0
https://pypi.org/project/zeekscript/1.2.0/
