### ISSUE TITLE
Formatting always inserts an empty line at end of file

### ISSUE THREAD

**Issue by bbannier** [zeek/zeekscript#8]
As of `zeek-format-1.1.0` formatting always inserts an empty line at the end of the file.

While including a trailing newline is a good idea, a trailing empty line is just noise. It would be great of `zeek-format` would not include it.

**Comment by ckreibich** [comment]
Benjamin could you share a before/after example? I've tried a couple of things and I'm not seeing trailing lines ... but I might just not be trying the right way. A simple example where this isn't happening:

```
$ echo "event zeek_init() { }" | zeek-format
event zeek_init()
{ }
```
Or, more explicitly:
```
$ echo "event zeek_init() { }" | zeek-format | xxd
00000000: 6576 656e 7420 7a65 656b 5f69 6e69 7428  event zeek_init(
00000010: 290a 7b20 7d0a                           ).{ }.
```
So here's a trailing newline, not a trailing empty line.

**Comment by bbannier** [comment]
Thanks for taking a look @ckreibich, I agree that `zeek-format` behaves as expected. My issue seems to be downstream in my editor integration. I am closing this.
